version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: cryptogoals_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptogoals
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    container_name: myodyssey_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cryptogoals?schema=public
    ports:
      - "3333:3333"
    volumes:
      - ./uploads:/app/uploads
    command: sh -c "npm run prisma:migrate && npm run prisma:generate && npm run build && npm run start"

volumes:
  db_data:
